//submit customer form (edit customer)
export const CUSTOMER_SUBMIT_FORM_REQUEST = 'CUSTOMER_SUBMIT_FORM_REQUEST'
export const CUSTOMER_SUBMIT_FORM_SUCCESS = 'CUSTOMER_SUBMIT_FORM_SUCCESS'
export const CUSTOMER_SUBMIT_FORM_FAILURE = 'CUSTOMER_SUBMIT_FORM_FAILURE'

// fetch and display existing customer
export const EXISTING_CUSTOMER_REQUEST = "EXISTING_CUSTOMER_REQUEST"
export const EXISTING_CUSTOMER_SUCCESS = "EXISTING_CUSTOMER_SUCCESS"
export const EXISTING_CUSTOMER_FAILURE = "EXISTING_CUSTOMER_FAILURE"
